// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPS6bYcd_l71eHd8kmdmV2OCKif8DteBU',
    appId: '1:495084237890:web:ad21159dc438effb5729db',
    messagingSenderId: '495084237890',
    projectId: 'zenworkfinal',
    authDomain: 'zenworkfinal.firebaseapp.com',
    storageBucket: 'zenworkfinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZUVqFkiX7gg1J3rUUN5z-rdvFMRdt6U',
    appId: '1:495084237890:android:64f0d469ba1b2d105729db',
    messagingSenderId: '495084237890',
    projectId: 'zenworkfinal',
    storageBucket: 'zenworkfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qRV0V4SXbjY2SunvZhDRR7QaJgDVJYs',
    appId: '1:495084237890:ios:69c767a45e14a35a5729db',
    messagingSenderId: '495084237890',
    projectId: 'zenworkfinal',
    storageBucket: 'zenworkfinal.firebasestorage.app',
    iosClientId: '495084237890-1kfv2jqjjbbtsjeqf1t5ld0jdf6rq9vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPS6bYcd_l71eHd8kmdmV2OCKif8DteBU',
    appId: '1:495084237890:web:fcf0754199a6617b5729db',
    messagingSenderId: '495084237890',
    projectId: 'zenworkfinal',
    authDomain: 'zenworkfinal.firebaseapp.com',
    storageBucket: 'zenworkfinal.firebasestorage.app',
  );
}
